version: '3.9'

services:
    node:
        build:
             context: .
        ports:
            - 3001:3000
        environment:
            - NODE_ENV=test
        volumes:
            - ./:/app
        depends_on: 
            - mysql
        command: npm run test-watch
    mysql:
        image: mysql
        env_file: ./.env
        environment: 
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: node
        ports:
            - 3307:3306
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config: